[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "sxwoba"
    name = "sxwOBA app"
    url = "https://sxwoba.herokuapp.com"
    weight = 3

[[main]]
    identifier = "cv"
    name = "CV"
    url = "/tags"
    weight = 4


# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/samueljwalsh"
    weight = 1

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/sam-walsh-585750168/"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/sam-walsh"
    weight = 3