[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "sxwoba"
    name = "sxwOBA app"
    url = "https://sxwoba.herokuapp.com"
    weight = 3

[[main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/sam-walsh-585750168/"
    weight = 4

[[main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/sam-walsh"
    weight = 5